Update INSTALLATION.md
I wasn't able to install on Kubuntu 20.04

ERROR: CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find KF5 (missing: Kirigami2) (found suitable version "5.68.0",
  minimum required is "5.48.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:22 (find_package)


Util i installed the dependency: kirigami2-dev

I saw im not the only on internet with this error.